# Form implementation generated from reading ui file 'temi.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 139)
        MainWindow.setMinimumSize(QtCore.QSize(678, 139))
        MainWindow.setStyleSheet("QMainWindow::title {\n"
"    background-color: #ffffff; /* Color blanco para la barra de título */\n"
"    color: #000000; /* Color del texto en la barra de título */\n"
"}\n"
"\n"
"/* MenuToolbar Style */\n"
"QMenuBar {\n"
"    background-color: #F0F0F0; \n"
"    border: 1px solid #CCCCCC; \n"
"}\n"
"\n"
"/* Style for menu elements */\n"
"QMenu {\n"
"    border: 1px solid #CCCCCC; \n"
"}\n"
"\n"
"/* Style for actions menu */\n"
"QAction {\n"
"    border: 1px solid #CCCCCC; \n"
"}\n"
"\n"
"#pushButton {\n"
"    background-color: #1DA1F2; /* Color azul similar al de Twitter */\n"
"    color: #ffffff; /* Texto en color blanco */\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #1DA1F2;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"    background-color: #0E71A7; /* Cambio de color al pasar el cursor */\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"    background-color: #0A5A7C; /* Cambio de color al presionar el botón */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(4, 63, 660, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(4, 0, 661, 30))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(14)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuLicense = QtWidgets.QMenu(parent=self.menubar)
        self.menuLicense.setObjectName("menuLicense")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_file = QtGui.QAction(parent=MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionPurchase = QtGui.QAction(parent=MainWindow)
        self.actionPurchase.setObjectName("actionPurchase")
        self.actionSet_License = QtGui.QAction(parent=MainWindow)
        self.actionSet_License.setObjectName("actionSet_License")
        self.actionTemi_Scrapper = QtGui.QAction(parent=MainWindow)
        self.actionTemi_Scrapper.setObjectName("actionTemi_Scrapper")
        self.menufile.addAction(self.actionOpen_file)
        self.menuLicense.addAction(self.actionPurchase)
        self.menuLicense.addAction(self.actionSet_License)
        self.menuAbout.addAction(self.actionTemi_Scrapper)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuLicense.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "temi-scrapped"))
        self.pushButton.setText(_translate("MainWindow", "Comenzar"))
        self.label.setText(_translate("MainWindow", "Sin archivo"))
        self.label_2.setText(_translate("MainWindow", "No soportado"))
        self.label_3.setText(_translate("MainWindow", "-"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Preprocesar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Importar a BD"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Importar a Excel"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuLicense.setTitle(_translate("MainWindow", "License"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionPurchase.setText(_translate("MainWindow", "Purchase"))
        self.actionSet_License.setText(_translate("MainWindow", "Set License"))
        self.actionTemi_Scrapper.setText(_translate("MainWindow", "Temi Scrapper"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
